apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    {{- include "webserver-deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webserver-deploy.selectorLabels" . | nindent 4 }}
