name: DB-tier Docker Image Publish and Deploy Database Helm Chart

on:
  workflow_dispatch:  # Manually trigger the workflow
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Ensure you have set up the following secrets in your GitHub repository:
      # DOCKERHUB_USERNAME: Your Docker Hub username.
      # DOCKERHUB_TOKEN : Your Docker Hub Token.
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: database-tier/Dockerfile
          push: true
          tags: |
            abhishekbhattu9/mediawiki-db:latest
            abhishekbhattu9/mediawiki-db:${{ github.run_number }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          install_kubectl: true

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: create directory kubernetes config file
        run: mkdir -p $HOME/.kube && touch $HOME/.kube/config

      - name: Configure kubectl
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Install Helm chart
        if: success()
        run: helm install my-release-${{ github.run_number }} ./k8s-helm-scripts/helm-database/database-deploy
