name: Web-tier Docker Image Publish and Deploy Web Helm Chart to AKS

on:
  workflow_dispatch:  # Manually trigger the workflow
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: web-tier/Dockerfile
          push: true
          tags: |
            abhishekbhattu9/mediawiki-web:latest
            abhishekbhattu9/mediawiki-web:${{ github.run_number }}
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          install_kubectl: true

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: create directory kubernetes config file
        run: mkdir -p $HOME/.kube && touch $HOME/.kube/config

      - name: Configure kubectl
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Install Helm chart
        run: helm install my-webrelease-${{ github.run_number }} ./k8s-helm-scripts/helm-webserver/webserver-deploy
